# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-30 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('wish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='add',
            field=models.ManyToManyField(related_name='add', to='login.User'),
        ),
    ]
